
package handlers

//code generated by 'go generate', do not edit

import (
	"github.com/jargv/plumbus"
	"net/http"
	"reflect"
	"encoding/json"
	"strconv"
	"fmt"
	"log"
)

// avoid unused import errors
var _ json.Delim
var _ log.Logger
var _ fmt.Formatter
var _ strconv.NumError

func init(){
	var dummy func(
		
			*amountQueryParam,
		
			*foodQueryParam,
		
	)(
		
	)

	typ := reflect.TypeOf(dummy)
	plumbus.RegisterAdaptor(typ, func(handler interface{}) http.HandlerFunc {
		callback := handler.(func(
			
				*amountQueryParam,
			
				*foodQueryParam,
			
		)(
			
		))

		return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request){
			
				queryParams := req.URL.Query()
			
			
			
				var arg0 *amountQueryParam
				  {
						
							if l, sent := queryParams["amount"]; sent && len(l) > 0 {
								queryInt, err := strconv.Atoi(l[0])
								if err != nil {
									plumbus.HandleResponseError(
										res, req,
										plumbus.Errorf(
											http.StatusBadRequest,
											"query param 'amount' expected to be integer value",
										),
									)
									return
								}
								arg0 = new(amountQueryParam)
								*arg0 = amountQueryParam(queryInt)
							}
						
					}
				
			
				var arg1 *foodQueryParam
				  
						if l, sent := queryParams["food"]; sent && len(l) > 0{
							arg1 = new(foodQueryParam)
							*arg1 = (foodQueryParam)(l[0])
						}
					
				
			

			
			

			callback(
				
					arg0,
				
					arg1,
				
			)

			
			

			
		})
	})
}
