
package handlers

//code generated by 'go generate', do not edit

import (
	"github.com/jargv/plumbus"
	"net/http"
	"reflect"
	"encoding/json"
	"strconv"
	"fmt"
	"log"
)

// avoid unused import errors
var _ json.Delim
var _ log.Logger
var _ fmt.Formatter
var _ strconv.NumError

func init(){
	var dummy func(
		
			ParamType,
		
			*ParamType,
		
	)(
		
	)

	typ := reflect.TypeOf(dummy)
	plumbus.RegisterAdaptor(typ, func(handler interface{}) http.HandlerFunc {
		callback := handler.(func(
			
				ParamType,
			
				*ParamType,
			
		)(
			
		))

		return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request){
			
			
			
				var arg0 ParamType
					
					if err := arg0.FromRequest(req); err != nil {
						plumbus.HandleResponseError(res, req, err)
						return
					}
				
			
				var arg1 *ParamType
					
						arg1 = new(ParamType)
					
					if err := arg1.FromRequest(req); err != nil {
						plumbus.HandleResponseError(res, req, err)
						return
					}
				
			

			
			

			callback(
				
					arg0,
				
					arg1,
				
			)

			
			

			
		})
	})
}
