
package handlers

//code generated by 'go generate', do not edit

import (
	"github.com/jargv/plumbus"
	"net/http"
	"reflect"
	"encoding/json"
	"fmt"
	"log"
)

// avoid unused import errors
var _ json.Delim
var _ log.Logger
var _ fmt.Formatter

func init(){
	var dummy func(
		
			body,
		
	)(
		
			interface {},
		
	)

	typ := reflect.TypeOf(dummy)
	plumbus.RegisterAdaptor(typ, func(handler interface{}) http.HandlerFunc {
		callback := handler.(func(
			
				body,
			
		)(
			
				interface {},
			
		))

		return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request){
			
			
				var arg0 body
				
					{
						if err := json.NewDecoder(req.Body).Decode(&arg0); err != nil {
							msg := fmt.Sprintf("{\"error\": \"decoding json: %s\"}", err.Error())
							http.Error(res, msg, http.StatusBadRequest)
							return
						}
					}
				
			

			
			
				result0  := 
			

			callback(
				
				arg0,
				
			)

			
			

			
				
					
						{
							if err := json.NewEncoder(res).Encode(result0); err != nil {
								plumbus.HandleResponseError(res, req, err)
								return
							}
						}
					
				
			
		})
	})
}
